# Generated by Django 6.1.1 on 2026-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The field is saved blog category', max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='The field is saved blog title', max_length=255, verbose_name='Blog Title')),
                ('description', models.TextField(help_text='The field is saved blog description', verbose_name='Blog Description')),
                ('image', models.ImageField(blank=True, help_text='The field is saved blog image', null=True, upload_to='blog_images/', verbose_name='Blog Image')),
                ('category', models.ManyToManyField(help_text='The field is saved blog category', to='blog.blogcategory', verbose_name='Blog Category')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
